# elliecoin steller toml
VERSION= "2.0.0"

ACCOUNTS=[
    "GDDXH3Z5G5KWTTNRCPRV574MBJ7VF6ARXNQNJ4FSZZCTBOOE3VJVXOJK",
    "GA2ZG5CI3UO7JJ5GIMACMVGPUR5UDDWRQGLED6Y632WTFPOBUBXXD5FW"
]

[DOCUMENTATION]
ORG_NAME="elliot"
ORG_URL=""
ORG_LOGO=""
ORG_DESCRIPTION="im just a person making a coin for me do not use this"
ORG_PHYSICAL_ADDRESS="somewhere in california"
ORG_PHONE_NUMBER="1 (831)-252-0604"
ORG_OFFICIAL_EMAIL="lord.elliot.the.great@gmail.com"